        <!-- JavaScript Includes -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

        <!-- Bootstrap JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
		<script src="/skolaverkefni/PhotoBase/assets/js/toucheffects.js"></script>
		<script src="/skolaverkefni/PhotoBase/assets/js/jquery.fancybox.js"></script>
		<script src="/skolaverkefni/PhotoBase/assets/js/jquery.fancybox.pack.js"></script>
		<script src="/skolaverkefni/PhotoBase/assets/js/Lazyload.js" type="text/javascript"></script>
        <script src="/skolaverkefni/PhotoBase/assets/js/modernizr.custom.js"></script>
