    <!-- Header -->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>PictureBase</title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

        <link href="/skolaverkefni/PhotoBase/assets/css/animated-masonry-gallery.css" rel="stylesheet">
        <link href="/skolaverkefni/PhotoBase/assets/css/Icomoon/style.css" rel="stylesheet">
        <link href="/skolaverkefni/PhotoBase/assets/css/custom.css" rel="stylesheet">
        <link href="/skolaverkefni/PhotoBase/assets/css/jquery.fancybox.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/skolaverkefni/PhotoBase/assets/css/component.css" />

    </head>
