        <!-- Navbar -->
        <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
            <?php if(Session::exists('success')): ?>
                <div class="alert alert-success" role="alert">
                    <div class="container">
                    <?php echo Session::flash('success') ?>
                    </div>
                </div>
            <?php endif; ?>
            <?php if(Session::exists('danger')): ?>
                <div class="alert alert-danger" role="alert">
                    <div class="container">
                    <?php echo Session::flash('danger') ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <?php if ($user->isLoggedIn()): ?>
                        <li><a href="/skolaverkefni/PhotoBase/myImages.php">Upload Image</a></li>
                        <?php endif; ?>
                    </ul>
                    <!--
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    -->
                    <ul class="nav navbar-nav navbar-right">
                    <?php if ($user->isLoggedIn()): ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $userData[4]; ?> <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li class=""><a href="/skolaverkefni/PhotoBase/myimages.php">My images</a></li>
                                <li><a href="/skolaverkefni/PhotoBase/app/logout.php">Logout</a></li>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <?php if (!$user->isLoggedIn()): ?>
                        <li><a data-toggle="modal" href='#login'>Login</a></li>
                        <li><a data-toggle="modal" href='#register'>register</a></li>
                    <?php endif; ?>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav> 
        <!-- navbar ends -->
